name: ci

on:
  push:
    branches:
      - dev

permissions:
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  docker:
    needs: [basic]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Sign In into Docker Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and push to Docker Registry
      - name: Docker - Build and Push - static-website
        uses: docker/build-push-action@v4
        with:
          # Путь в котором будут выполняться комманды для сборки
          context: ./backend/websocket
          file: ./backend/websocket/docker/prod/Dockerfile
          push: true
          tags: docker-registry.toxiccat.ru/twitch-chat-bot:latest

  # Автоматическое создание Pull Request'a из DEV ветки в MAIN
  # Автоматический merge Pull Request'a
  auto-pr-mr:
    needs: [basic, docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto Pull Request Create
        run: gh pr create --title "Auto PR from DEV to MAIN"
          --body "Auto request from CI/CD"

      - name: Auto Merge Pull Request
        run: gh pr merge --auto --merge
